### ISSUE TITLE
Cannot run the commands according to the website instructions

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.CodeAuditor#207]
@bfabiny @tombui99 
Hi Guys,

I tried to run CodeAuditor as per https://codeauditor.com/

I tried both the command $ docker container run --cap-add=SYS_ADMIN sswconsulting/codeauditor --lighthouse --url <URL>
and docker run sswconsulting/codeauditor --url <URL>

Docker is installed.

1. Please review the below image and either fix the bug or the instructions on the CodeAuditor website.

![image](https://user-images.githubusercontent.com/79821522/114954102-24d62480-9e9d-11eb-9527-706e208a2601.png)
Figure: The issue I face trying to run CodeAuditor

**Comment by bfabiny** [comment]
Hey @pierssinclairssw,

The issue you are seeing is because the url parameter passed to the docker command does not contain the protocol (either http or https).

If you run the following command, CodeAuditor will scan the SSW Rules site 

`docker run sswconsulting/codeauditor --url http://ssw.com.au/rules/`

I have logged GitHub Issue #212 to make the instructions clearer and add validation on the url parameter.

**Comment by tombui99** [comment]
Closed as this item has been resolved
