### ISSUE TITLE
BUG - URLs with "?" in them are being wrongly shown as error

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#226]
### Hi CodeAuditor team, 

On this rule, for example, https://www.ssw.com.au/rules/do-you-use-the-official-mobile-app-for-crm

If you look at this link:

> Android: [Dynamics 365 - Google Play Store](https://play.google.com/store/apps/details?id=com.microsoft.crm.crmphone)
<img width="1004" alt="Screen Shot 2021-05-26 at 3 12 19 PM" src="https://user-images.githubusercontent.com/12601228/119738534-b2f6e080-be35-11eb-9c38-9f9558cc0029.png">

The link works fine, however, CodeAuditor is catching it as a 404:
<img width="1275" alt="Screen Shot 2021-05-26 at 3 15 23 PM" src="https://user-images.githubusercontent.com/12601228/119738223-36640200-be35-11eb-9ade-fb6146cfcdc9.png">

I believe the issue is that CodeAuditor is ignoring everything after the symbol "?" in the link

so instead of the full link:
https://play.google.com/store/apps/details?id=com.microsoft.crm.crmphone (works fine)

it reads:
https://play.google.com/store/apps/details (404 error)

1. Please make sure CodeAuditor is able to read **full links** (that have "?") and don't give these false positives

Cheers,
Tiago

**Comment by tombui99** [comment]
Hi @tiagov8 

> Please make sure CodeAuditor is able to read full links (that have "?") and don't give these false positives

Done - Fixed CodeAuditor so that it now reads the entire URL query that have "?"

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/67776356/122310126-fafbb580-cf52-11eb-917e-dfc7274cfac7.png">

**Figure: URL with "?" is now fully read and shows no error https://codeauditor.com/build/49e3b023-9422-4fec-4290-52b660a19622**
