### ISSUE TITLE
HTML Rule - Check for Figures, Tips and Notes that aren't on a new line

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.CodeAuditor#232]
cc: @adamcogan @christianmorfordwaitessw @pierssinclairssw @tombui99

As per our conversation, this was a problem with the extraction from SharePoint. A new HTML rule should be created to find and fix all occurrences of this problem.

To @tombui99 (with @bradystroud),

1. Add a HTML rule to check for Figures, Tips and Notes that aren't on a new line

Bad example below - https://www.ssw.com.au/rules/do-you-leave-messages-when-your-phone-call-is-unanswered
> Your messages must contain your name (firstname and lastname), purpose of calling, andyour contact number. Create a sense of urgency by giving them explicit time frames when you are available. Hi Ms. Emma, this is Alvin. Please call me back, thanks. **Figure: Bad Example - lacking in communication details, reason for calling and sense of urgency**

Good example below - https://www.ssw.com.au/rules/meetings-do-you-go-to-meetings-prepared 
> So you are talking to a client about their ice cream chain? How many outlets do you have?
> Where is the main outlet?
> **Figure: Bad examples - you should already know the answers to these questions by use of research tools such as the Internet**

Another good example - https://www.ssw.com.au/rules/have-standard-tables-and-columns

2. After adding the rule, run CodeAuditor on SSW Rules and see how many it finds

3. Get @tiagov8 to fix the issues

Thanks,

-Brady

**Comment by tombui99** [comment]
Hi @bradystroud 
CC @adamcogan 

I've tried to create a custom rule to check for Figure statements that aren't on a new line and I don't think it's possible to do it.
This is because we cannot tell from the HTML whether a tag is on a new line unless it is a whole sentences

<img width="924" alt="image" src="https://user-images.githubusercontent.com/67776356/120428907-d5e63f00-c3b7-11eb-90cc-c0fbd7f642b5.png">

**Figure: Figure statement on new line**
 
<img width="887" alt="image" src="https://user-images.githubusercontent.com/67776356/120428986-fa421b80-c3b7-11eb-9d88-4e1f2e21ef64.png">

**Figure: Figure statement on the same line**

**Comment by tombui99** [comment]
Hi @bradystroud 

I've also tried to to track the "Figure" text that has a specific tag before it.

However, due to the limitation of the HTMLHint library, it cannot check a text and a tag together

<img width="477" alt="image" src="https://user-images.githubusercontent.com/67776356/120580075-e6f08800-c46b-11eb-83a3-f1c1e1a0b1f1.png">

**Figure: Text is under tag thus cannot be tracked**

**Comment by bradystroud** [comment]
cc: @nvhoanganh 
Hi @tombui99,

The rule should check where there is a `<strong>Figure:` and no `<br>` or `</a>` or `</img>` or `</div` or `</p>` before it.

That should find all the Figures that aren't on a new line. 

1. Please implement this rule

**Comment by tombui99** [comment]
> Please implement this rule

Done - new rule added to check for Figure statements

<img width="959" alt="image" src="https://user-images.githubusercontent.com/67776356/121612852-9f3ab380-ca9e-11eb-9f7e-685593f5fffb.png">

**Figure: CodeAuditor checks for Figure statements that are not wrapped in correct tag https://codeauditor.com/htmlhint/5e176908-9a3e-4385-bdd4-37790f3b69f5**
