### ISSUE TITLE
🐛 Enabled rules - Scan not using configuration

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.CodeAuditor#361]
Hi @tombui99 

### Describe the Bug
CodeAuditor doesn't seem to be using the "Enabled Rules" configuration. 

![image](https://user-images.githubusercontent.com/38869720/180386754-c9942b10-336e-47b9-9281-bbaa5520ac80.png)
**Figure: Rule was disabled, but still showing up in scan**

### To Reproduce
1. Go to https://codeauditor.com/htmlhint/249d23d4-cebd-46c7-63e0-8c70e10f8641
2. Click on `Enabled Rules`
3. Disable a rule
4. Do another scan
5. Errors/warnings for that rule still appear

### Expected Behavior
No Errors/warnings are shown for the disabled rule

### Tasks
- [ ] Investigate
- [ ] Fix

Thanks!

**Comment by bradystroud** [comment]
Hey @tombui99 this one is important for us to get CodeAuditor to 0
https://github.com/SSWConsulting/SSW.Rules/issues/869

Could you provide an estimate on when this could be complete?

Thanks 🙂

**Comment by tombui99** [comment]
Hi @bradystroud 
CC @adamcogan 

> Fixed it so that each scan shows the correct rules configuration

Done - I have fixed this bug by updating the data structure in our database so that it records all the html rules that have been applied on each scan. From now on each scan will show the correct rules configuration that has been applied on it.

![image](https://user-images.githubusercontent.com/67776356/182802708-04fb7fc6-24ed-44ff-8513-ea96556a36e9.png)

**Figure: Rules are now correctly displayed**
