### ISSUE TITLE
🐛  Broken links count is wrong

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.CodeAuditor#362]
Hi @tombui99 

### Describe the Bug

Links count is different to amount of listed links

![Screen Shot 2022-07-27 at 11 46 43 am](https://user-images.githubusercontent.com/38869720/181142622-8f60826d-e609-4bf7-8f4d-af35c6cadf02.png)
**Figure: Broken links count is 5, but there are only 3 links**

### To Reproduce
1. Go to https://codeauditor.com/build/73193441-d57f-467f-4cf7-0f0889c13751
1. See Links (5) but only 3 links listed

### Expected Behavior
Count is same as the number of links

### Tasks
- [ ] Fix

Thanks!

**Comment by tombui99** [comment]
Hi @bradystroud ,
cc @adamcogan 

> Fix so that Count is same as the number of links

Done - I have fixed it so that the number of Count is same as the number of broken links

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/67776356/181489242-c574a716-f94c-435c-8e9e-da144e7f8f0a.png">


**Figure: Consistent number of Count and broken links**

**Comment by bradystroud** [comment]
Hey @tombui99 Thanks for this! looks like its working now.
I found a related issue.

When I'm viewing the list of scans for a site, the broken link count is different when I open the scan.
See demo -
![ezgif-3-a60a9abd00](https://user-images.githubusercontent.com/38869720/181677432-4906f159-2d21-4f49-969a-774bda6674d4.gif)

- [ ] Please investigate and fix

Thanks

**Comment by tiagov8** [comment]
Hey @tombui99 

Different count on the [last report](https://codeauditor.com/build/d6eff9ee-af95-4ffe-d910-cde07dd08666): 18 x 8
I'm repopening this Issue

1. Please investigate and fix

<img width="1342" alt="Screenshot 2023-01-17 at 2 18 09 PM" src="https://user-images.githubusercontent.com/12601228/213024909-8936cffa-491a-432a-b936-9e3aa44a86a8.png">

<img width="1323" alt="Screenshot 2023-01-17 at 2 18 16 PM" src="https://user-images.githubusercontent.com/12601228/213024906-721a67a0-5e58-430d-8259-22981d04b7da.png">

**Comment by tombui99** [comment]
Hi @tiagov8 and @bradystroud 

> Investigate and fix wrong broken link counts

Done - the latest results are now showing consistent numbers across the pages

Previously, due to the huge number of links in SSW Rules, there were network issues within Docker that caused the inconsistent numbers of links summary across the pages - it is running consistently now

**Comment by tombui99** [comment]
CC @adamcogan 

Closing as issue has been resolved
