### ISSUE TITLE
♻️ Make sure CodeAuditor "Scrum terms" are aligned with the SSW Rule

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#423]
Cc: @adamcogan 

Hi @tombui99 

### Pain
The highlighted line was caught by CodeAuditor as an error for Scrum terms:
https://ssw.com.au/rules/management-do-you-have-a-release-update-debrief-meeting-on-a-weekly-basis/

<img width="1205" alt="Screenshot 2023-04-04 at 7 25 23 PM" src="https://user-images.githubusercontent.com/12601228/229936397-a2f55f47-bf4e-4d6c-9855-888bc7f4b4d1.png">

I don't see any of the terms from https://ssw.com.au/rules/scrum-should-be-capitalized/ in that sentence 

### Tasks
- [ ] Make sure CodeAuditor "Scrum terms" are aligned with the SSW Rules
- [ ] Update the rule if needed

Thanks!

**Comment by tombui99** [comment]
Hey @tiagov8 
CC @adamcogan @william-liebenberg 

> Make sure CodeAuditor "Scrum terms" are aligned with the SSW Rules

Done - I have double-checked and made sure the terms are aligned with SSW Rules

> Investigate why CodeAuditor reported the line as using wrong Scrum terms

After investigating, I found that CodeAuditor was actually highlighting the URL above which contains the term "Sprint Retrospective" in lower case.

The reason why the line below was also highlighted is because in the rendered HTML of the page, both of the HTML tags sit on the same line.

![image](https://user-images.githubusercontent.com/67776356/232397454-12f580b0-6111-4660-bb77-f3d86dfe014a.png)

**Figure: Report result of the incorrect scrum term**

**Comment by tiagov8** [comment]
Hey @tombui99 

I understand this is a Code Auditor bug - to highlight a Content issue (Scrum term) inside a HTML link tag. 
This should only be caught in content text... like headings, lists, paragraphs, etc

1. Please make sure this has been fixed

**Comment by tombui99** [comment]
Hi @tiagov8 
cc @adamcogan @william-liebenberg 

> Make sure this has been fixed

Done - I have fixed the custom rule so now it will not check the Scrum terms in any `<a>` tag or `href`

I have re-run a scan on the Rule page and it no longer reports the Scrum term error
See https://codeauditor.com/htmlhint/bd781849-a248-4342-8510-6b70e7db741b?displayMode=1

Please let me know if there's anything!
