### ISSUE TITLE
♻️ SSW.Rules links being scanned on SSW.Website runs

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#453]
Cc: @adamcogan 

Hi @tombui99 

### Pain
On the latest SSW.Website run there is a broken link from SSW.Rules
https://codeauditor.com/build/1d503730-1c18-42f4-093a-6b62fa4227a1

<img width="1390" alt="Screenshot 2023-05-15 at 11 01 13 AM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/3148b59c-6ab8-4c94-9114-32cdf0552dfb">

### What code could be improved?
We should see this error on a SSW.Rules scan

### Tasks
- [ ] Can we avoid ssw.com.au/rules on ssw.com.au scans?
- [ ] What is the reason the error above is NOT shown on SSW.Rules latest scan?  
   https://codeauditor.com/build/1c6978df-cf96-4c28-371b-93b78d41a8a3

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 
cc @adamcogan @william-liebenberg 

> Can we avoid ssw.com.au/rules on ssw.com.au scans?

After investigating with our code scanning tool, we cannot avoid including SSW Rules in SSW Website scans because the links to SSW Rules are actually included in SSW Website main page. Therefore, CodeAuditor will scrape and scan all the links it could find in SSW Website page.

![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/48c94f1c-04df-4a6e-9d4b-061e3e53bf39)

**Figure: SSW Rules link are included in SSW Website main page**

> What is the reason the error above is NOT shown on SSW.Rules latest scan?

The scan you were looking at was 7 days ago - I just did a rescan on SSW Rules and it was able to find the broken link
https://codeauditor.com/build/ce0bbefe-96be-4ba7-4b01-b348be7fbd89

![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/1beda739-2fd6-4dab-ae71-3a23af74ed55)

**Figure: Similar broken link found in latest SSW Rules scan**

Feel free to reopen if you have any further issues.
