### ISSUE TITLE
🐛 Lighthouse failure

### ISSUE THREAD

**Issue by AlexRothwell** [SSWConsulting/SSW.CodeAuditor#455]
Cc: @tombui99 @adamcogan @william-liebenberg 

Hi Tom

### Describe the Bug

When launching CodeAuditor following the provided instructions, it encounters an error stating that lighthouse failed

### To Reproduce
1. Run `docker run sswconsulting/codeauditor --token {{ TOKEN }} --url https://www.ssw.com.au`
1. See error

### Expected Behavior

Error should not occur

### Tasks
- [ ] Investigate
- [ ] Fix

### Environment
 - Device: [e.g. iPhone 12]
 - OS: Windows 11 22H2 (10.0.22621.1702)
 - Docker version: 4.19.0
 - WSL version: 1.0.3.0

### Screenshots

![image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/7465195/0bf67598-13f0-437d-a782-8da3ef827ec9)
**Figure: The error and stacktrace encountered**

Thanks!

**Comment by tombui99** [comment]
Hey @AlexRothwell 
cc @william-liebenberg @adamcogan 

Sorry for the delay but this issue took quite a while to investigate and fix.

We have updated the Dockerfile to use Chromium and Puppeteer dependencies so that Lighthouse runs correctly under headless Chrome.

You will also have to use the new docker command to run:
`docker container run --cap-add=SYS_ADMIN sswconsulting/codeauditor --token <Token> --url <URL>`

Let me know if you may find any other issue!

Thanks a lot!
