### ISSUE TITLE
💄 What page am I on?

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.CodeAuditor#479]
Cc: @BrookJeynes 

Hi @tombui99 

<img width="1292" alt="image" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/38869720/baf843bc-e400-45ee-b812-62d2fca0a3d6">

**Figure: Not clear what page I am on**
### Tasks
- [ ] Indicate what page I am on (maybe make menu item red)

Thanks!

**Comment by tombui99** [comment]
Hi @bradystroud 
cc @william-liebenberg @adamcogan @BrookJeynes 

> Indicate what page I am on (maybe make menu item red)

Done - I have fixed it so that the menu item on the navbar has red text if the user is on that page

![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/67776356/ae9ca58c-352b-4238-9588-b37c056d6f2b)

**Figure: Menu item text in red when user is on the page**
