### ISSUE TITLE
🐛 Can we make CodeAuditor ignore "authentication required" links?

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#544]
Cc: @adamcogan @JeanThirion 

Hi @tombui99 

### Describe the Bug

The link here https://www.ssw.com.au/rules/teams-usage/#tenant-usage 
...requires authentication (special permissions) and it's being caught as broken by CodeAuditor

1. Can we make CodeAuditor ignore "authentication-required" links?

### Tasks
- [ ] Investigate
- [ ] Fix

Thanks!

Related: https://github.com/SSWConsulting/SSW.Rules.Content/pull/6018

<img width="1199" alt="Screenshot 2023-07-19 at 9 53 09 AM" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/12601228/074f0c46-bb4f-4665-abfe-b5a85028fedd">

**Comment by zacharykeeping** [comment]
Hey @tiagov8 

For the link you posted, that's already in the "unscannable links" list so with Tom's changes for #549 that link will now appear in that section rather than appear broken.

Trying to dig into this deeper, I'm not sure there's any other way we could handle a link like that specifically. The link checking code does a HEAD request on every link and it appears that any HEAD requests to that link will always return a 404 (I'm assuming this is the reason it's already considered unscannable). I've only been able to get an OK result when doing a full GET request, but it would obviously be much less efficient to return a GET response for every link. Perhaps we could check HEAD then retry using GET on an error response, but I imagine this would still have a performance impact that perhaps might not be worth it.

So I think for now with Tom's change correctly showing unscannable links in the frontend this should be covered off okay, but perhaps if we start seeing more of these kinds of links pop up in the future it might be worth revisiting.
