### ISSUE TITLE
♻️ UI - Improve Custom rules on the scan section

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.CodeAuditor#599]
cc: @william-liebenberg @adamcogan @tombui99 @tiagov8 @bradystroud 

- [x] Update HTML Rules Scanned section to be consistent with Enable/Disable Rules UI.

![Image](https://user-images.githubusercontent.com/11418832/262189706-7c4de7d8-02b4-4ebf-9e9b-3ce5069e0ac8.png)

**Figure: Section to be updated to match Enable/Disable Rules UI**

**Comment by zacharykeeping** [comment]
Done - this has been updated to include the relevant icons.



![Image](https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/a3c31ff4-356a-44d9-8d98-c02e7bcf7cfa)

**Figure: HTML Rules Scanned section with icons**

**Comment by tiagov8** [comment]
Hi @zacharykeeping 

- [ ] 1. The space between the icon and prefix should NOT be underlined. Can you fix?

- [ ] 2. Should this be a numbered list? I think so... Double check with Adam and action if agreed

- [ ] 3. Change from

  
  ```
  <div class="text-left">
  <span class="font-sans text-lg pt-2">Build Version: 1.0.0</span>
  </div>
  ```

to

  ```
  <div class="py-4">
  <p>Build Version: 1.0.0</p>
  </div>
  ```

Looking at this related view "Enable/Disable Rules:" popup

- [ ] 4. Please also remove the underline from the space betweeen icon and text

Looking at this other related view page https://codeauditor.com/rules 

- [ ] 5. Make sure the texts are underlined (since they are links)

- [ ] 6. Please also remove the underline from the space betweeen icon and text

- [ ] 7. Fix the numbered list to use the right HTML syntax from

 
```
<ol><li>...</li></ol>
<ol><li>...</li></ol>
<ol><li>...</li></ol>
<ol><li>...</li></ol>
```

to

```
<ol>
<li>...</li>
<li>...</li>
<li>...</li>
<li>...</li>
</ol>
```

**Comment by zacharykeeping** [comment]
All done - these changes have been implemented.

<img width="574" alt="Screenshot 2023-08-30 at 2 22 06 pm" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/e5e5e3c1-52cf-4beb-881a-6a654665446b">

**Figure: Cleaner underlining and numbering**

<img width="568" alt="Screenshot 2023-08-30 at 2 23 12 pm" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/209bf046-7792-4c73-b989-92ff40a59433">

**Figure: Cleaner underlines**

<img width="749" alt="Screenshot 2023-08-30 at 2 34 34 pm" src="https://github.com/SSWConsulting/SSW.CodeAuditor/assets/11418832/7fcd34d0-4b98-494f-acfa-9d292c08ff8a">

**Figure: Rules page links are now underlined**
